import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { navigateBack } from '../src/utils/navigation';

export default function PrivacyPolicyScreen() {
  const router = useRouter();

  return (
    <View style={styles.container}>
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        <View style={styles.content}>
          <Text style={styles.title}>Privacy Policy</Text>
          
          <View style={styles.section}>
            <Text style={styles.text}>
              Last updated: August 4, 2025
            </Text>
            <Text style={styles.text}>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </Text>
            <Text style={styles.text}>
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Interpretation and Definitions</Text>
            
            <Text style={styles.subsectionTitle}>Interpretation</Text>
            <Text style={styles.text}>
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </Text>
            
            <Text style={styles.subsectionTitle}>Definitions</Text>
            <Text style={styles.text}>
              For the purposes of this Privacy Policy:
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Account</Text> means a unique account created for You to access our Service or parts of our Service.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Affiliate</Text> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Platform</Text> (referred to as either "the Platform", "We", "Us" or "Our" in this Agreement) refers to Stefna.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Cookies</Text> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Device</Text> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Personal Data</Text> is any information that relates to an identified or identifiable individual.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Service</Text> refers to the Website, Stefna, an AI-powered photo and video editing platform.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Service Provider</Text> means any natural or legal person who processes the data on behalf of the Platform. It refers to third-party companies or individuals employed by the Platform to facilitate the Service, to provide the Service on behalf of the Platform, to perform services related to the Service or to assist the Platform in analyzing how the Service is used.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Usage Data</Text> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>Website</Text> refers to Stefna, accessible from stefna.xyz
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>You</Text> means the individual accessing or using the Service, or the Platform, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Collecting and Using Your Personal Data</Text>
            
            <Text style={styles.subsectionTitle}>Types of Data Collected</Text>
            
            <Text style={styles.text}>
              <Text style={styles.bold}>Personal Data</Text>
            </Text>
            <Text style={styles.text}>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </Text>
            <Text style={styles.bulletPoint}>
              • Email address
            </Text>
            <Text style={styles.bulletPoint}>
              • Usage data
            </Text>
            
            <Text style={styles.text}>
              <Text style={styles.bold}>Usage Data</Text>
            </Text>
            <Text style={styles.text}>
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Use of Your Personal Data</Text>
            <Text style={styles.text}>
              The Platform may use Personal Data for the following purposes:
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>To provide and maintain our Service</Text>, including to monitor the usage of our Service.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>To manage Your Account:</Text> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>For the performance of a contract:</Text> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>To contact You:</Text> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>To provide You</Text> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>To manage Your requests:</Text> To attend and manage Your requests to Us.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>For business transfers:</Text> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
            </Text>
            <Text style={styles.bulletPoint}>
              • <Text style={styles.bold}>For other purposes:</Text> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Contact Us</Text>
            <Text style={styles.text}>
              If you have any questions about this Privacy Policy, You can contact us:
            </Text>
            <Text style={styles.bulletPoint}>
              • By email: hello@stefna.xyz
            </Text>
          </View>

          <View style={styles.footer}>
            <Text style={styles.footerText}>Last updated: August 4, 2025</Text>
          </View>
        </View>
      </ScrollView>

      {/* Floating Back Button */}
      <View style={styles.headerRow}>
        <TouchableOpacity style={styles.iconBackButton} onPress={() => navigateBack.toMain()}>
          <Feather name="arrow-left" size={20} color="#ffffff" />
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scrollView: {
    flex: 1,
    paddingTop: 60,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 24,
    textAlign: 'center',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 12,
  },
  subsectionTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#ffffff',
    marginTop: 12,
    marginBottom: 8,
  },
  text: {
    fontSize: 14,
    color: '#cccccc',
    lineHeight: 20,
    marginBottom: 12,
  },
  bulletPoint: {
    fontSize: 14,
    color: '#cccccc',
    lineHeight: 20,
    marginBottom: 8,
    paddingLeft: 8,
  },
  bold: {
    fontWeight: '600',
    color: '#ffffff',
  },
  footer: {
    marginTop: 32,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#333333',
  },
  footerText: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
  },
  headerRow: { 
    position: 'absolute', 
    top: 0, 
    left: 0, 
    right: 0, 
    paddingTop: 40, 
    paddingLeft: 8, 
    zIndex: 1000 
  },
  iconBackButton: { 
    width: 36, 
    height: 36, 
    borderRadius: 18, 
    backgroundColor: '#000000', 
    alignItems: 'center', 
    justifyContent: 'center' 
  },
});