name: EAS Update (development)

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install EAS CLI
        run: npm i -g eas-cli
      - name: Install deps
        run: npm ci
      - name: Debug repo state
        run: |
          git rev-parse HEAD
          ls -la assets | cat
          sed -n '1,60p' app/welcome.tsx | cat
      - name: Publish OTA update to development
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
          EAS_NO_VCS: 1
        run: npx eas update --auto --branch development --message "Auto OTA from main"
